name: side_sheet
description: "Flutter package for Material Design 3 modal side sheets with customizable title, body, and actions."
version: 0.0.5
homepage: https://github.com/rsoft-in/side_sheet

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
